name: LDS General Conference Humor
favicon: null
layout_spectrum: 0.90912
typography_spectrum: 0.71068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#813913'
    - '#937a62'
    - '#d5cabe'
    - '#775d4a'
  brandStrength: 0.6829074502456933
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
