name: LDS General Conference Humor
favicon: null
layout_spectrum: 0.1762410590890795
typography_spectrum: 0.7380838862154633
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6829074502456933
  lightness: 0.018153819488361478
  saturation: 0.30077881226316094
  rhythmicContrast: 0.8158151444513351
purpose: []
